package chml;

import java.awt.*;
import javax.swing.*;

public class MainWindow extends javax.swing.JFrame {

    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QVDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DBtnOK = new javax.swing.JButton();
        DBtnCancel = new javax.swing.JButton();
        DVQ = new javax.swing.JSpinner();
        bgDrawModeSelect = new javax.swing.ButtonGroup();
        bgFieldTypeSelect = new javax.swing.ButtonGroup();
        QRDialog = new javax.swing.JDialog();
        pnlQPosNeg = new javax.swing.JPanel();
        DRQ = new javax.swing.JSpinner();
        DRBtnOK = new javax.swing.JButton();
        DRBtnDel = new javax.swing.JButton();
        pnlBackground = new javax.swing.JPanel();
        ScrPanel = new Scr();
        pnlTools = new javax.swing.JPanel();
        pnlRedraw = new javax.swing.JPanel();
        btnRedraw = new javax.swing.JButton();
        btnFastRedraw = new javax.swing.JButton();
        slRFP = new javax.swing.JSlider();
        pnlChrgMouse = new javax.swing.JPanel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        pnlDM = new javax.swing.JPanel();
        DM1 = new javax.swing.JRadioButton();
        DM2 = new javax.swing.JRadioButton();
        DM3 = new javax.swing.JRadioButton();
        DM4 = new javax.swing.JRadioButton();
        slDrawMode = new javax.swing.JSlider();
        pnlLoF = new javax.swing.JPanel();
        cbLoF = new javax.swing.JCheckBox();
        slLoF = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        mbMain = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        QVDialog.setLocation(new java.awt.Point(100, 100));
        QVDialog.setResizable(false);
        QVDialog.setSize(new java.awt.Dimension(252, 146));

        jLabel1.setText("Введите значение добавляемого заряда");

        DBtnOK.setText("OK");
        DBtnOK.setName(""); // NOI18N
        DBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBtnOKActionPerformed(evt);
            }
        });

        DBtnCancel.setText("Cancel");
        DBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBtnCancelActionPerformed(evt);
            }
        });

        DVQ.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 1.0f));
        DVQ.setToolTipText("efwef");
        DVQ.setBorder(new javax.swing.border.MatteBorder(null));
        DVQ.setEditor(new javax.swing.JSpinner.NumberEditor(DVQ, "#,##0.#####"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DVQ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DVQ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DBtnCancel)
                    .addComponent(DBtnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");
        DBtnOK.getAccessibleContext().setAccessibleName("");
        DBtnCancel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout QVDialogLayout = new javax.swing.GroupLayout(QVDialog.getContentPane());
        QVDialog.getContentPane().setLayout(QVDialogLayout);
        QVDialogLayout.setHorizontalGroup(
            QVDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QVDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        QVDialogLayout.setVerticalGroup(
            QVDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QVDialogLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pnlQPosNeg.setBackground(new java.awt.Color(102, 102, 255));

        DRQ.setModel(new javax.swing.SpinnerNumberModel(1.0f, null, null, 1.0f));
        DRQ.setToolTipText("efwef");
        DRQ.setBorder(new javax.swing.border.MatteBorder(null));
        DRQ.setEditor(new javax.swing.JSpinner.NumberEditor(DRQ, "#,##0.#####"));

        javax.swing.GroupLayout pnlQPosNegLayout = new javax.swing.GroupLayout(pnlQPosNeg);
        pnlQPosNeg.setLayout(pnlQPosNegLayout);
        pnlQPosNegLayout.setHorizontalGroup(
            pnlQPosNegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQPosNegLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(DRQ)
                .addGap(4, 4, 4))
        );
        pnlQPosNegLayout.setVerticalGroup(
            pnlQPosNegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQPosNegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DRQ, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DRBtnOK.setText("OK");
        DRBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRBtnOKActionPerformed(evt);
            }
        });

        DRBtnDel.setText("Del");
        DRBtnDel.setActionCommand("");
        DRBtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DRBtnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QRDialogLayout = new javax.swing.GroupLayout(QRDialog.getContentPane());
        QRDialog.getContentPane().setLayout(QRDialogLayout);
        QRDialogLayout.setHorizontalGroup(
            QRDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QRDialogLayout.createSequentialGroup()
                .addComponent(DRBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DRBtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(pnlQPosNeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QRDialogLayout.setVerticalGroup(
            QRDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QRDialogLayout.createSequentialGroup()
                .addComponent(pnlQPosNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(QRDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DRBtnOK)
                    .addComponent(DRBtnDel))
                .addGap(0, 0, 0))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChMl project");
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 460));
        setName("wndMain"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(153, 153, 153));

        ScrPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ScrPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ScrPanel.setCursor(cursor);
        ScrPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ScrPanelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ScrPanelMouseMoved(evt);
            }
        });
        ScrPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ScrPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ScrPanelLayout = new javax.swing.GroupLayout(ScrPanel);
        ScrPanel.setLayout(ScrPanelLayout);
        ScrPanelLayout.setHorizontalGroup(
            ScrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );
        ScrPanelLayout.setVerticalGroup(
            ScrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlRedraw.setBackground(new java.awt.Color(102, 102, 102));
        pnlRedraw.setToolTipText(" ");
        pnlRedraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRedrawMouseClicked(evt);
            }
        });

        btnRedraw.setBackground(new java.awt.Color(51, 51, 51));
        btnRedraw.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnRedraw.setForeground(new java.awt.Color(255, 255, 255));
        btnRedraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reficon.png"))); // NOI18N
        btnRedraw.setText("  REDRAW");
        btnRedraw.setActionCommand("    REDRAW");
        btnRedraw.setBorder(null);
        btnRedraw.setBorderPainted(false);
        btnRedraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedrawActionPerformed(evt);
            }
        });

        btnFastRedraw.setBackground(new java.awt.Color(102, 102, 102));
        btnFastRedraw.setForeground(new java.awt.Color(255, 255, 255));
        btnFastRedraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reficon22.png"))); // NOI18N
        btnFastRedraw.setText("   FAST REDRAW");
        btnFastRedraw.setActionCommand(" FAST REDRAW");
        btnFastRedraw.setPreferredSize(new java.awt.Dimension(139, 36));
        btnFastRedraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFastRedrawActionPerformed(evt);
            }
        });

        slRFP.setForeground(new java.awt.Color(102, 102, 102));
        slRFP.setMaximum(6);
        slRFP.setMinimum(2);
        slRFP.setPaintLabels(true);
        slRFP.setPaintTicks(true);
        slRFP.setToolTipText("");
        slRFP.setValue(4);
        slRFP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slRFPStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlRedrawLayout = new javax.swing.GroupLayout(pnlRedraw);
        pnlRedraw.setLayout(pnlRedrawLayout);
        pnlRedrawLayout.setHorizontalGroup(
            pnlRedrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRedraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFastRedraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slRFP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlRedrawLayout.setVerticalGroup(
            pnlRedrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRedrawLayout.createSequentialGroup()
                .addComponent(btnRedraw, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnFastRedraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(slRFP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlChrgMouse.setBackground(new java.awt.Color(102, 102, 102));

        jFormattedTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField1.setText("1.000");
        jFormattedTextField1.setAlignmentX(0.0F);
        jFormattedTextField1.setAlignmentY(0.0F);
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(34, 29));

        jToggleButton1.setBackground(new java.awt.Color(51, 51, 51));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_cur.png"))); // NOI18N
        jToggleButton1.setText(" like charge");
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToggleButton1.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jToggleButton1.setMaximumSize(new java.awt.Dimension(87, 27));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(87, 0));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(87, 30));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChrgMouseLayout = new javax.swing.GroupLayout(pnlChrgMouse);
        pnlChrgMouse.setLayout(pnlChrgMouseLayout);
        pnlChrgMouseLayout.setHorizontalGroup(
            pnlChrgMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChrgMouseLayout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChrgMouseLayout.setVerticalGroup(
            pnlChrgMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChrgMouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlDM.setBackground(new java.awt.Color(102, 102, 102));

        DM1.setBackground(new java.awt.Color(102, 102, 102));
        bgDrawModeSelect.add(DM1);
        DM1.setForeground(new java.awt.Color(255, 255, 255));
        DM1.setText("Cubic dependence");
        DM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DM1ActionPerformed(evt);
            }
        });

        DM2.setBackground(new java.awt.Color(102, 102, 102));
        bgDrawModeSelect.add(DM2);
        DM2.setForeground(new java.awt.Color(255, 255, 255));
        DM2.setSelected(true);
        DM2.setText("Linear dependence");
        DM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DM2ActionPerformed(evt);
            }
        });

        DM3.setBackground(new java.awt.Color(102, 102, 102));
        bgDrawModeSelect.add(DM3);
        DM3.setForeground(new java.awt.Color(255, 255, 255));
        DM3.setText("Combined mode");
        DM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DM3ActionPerformed(evt);
            }
        });

        DM4.setBackground(new java.awt.Color(102, 102, 102));
        bgDrawModeSelect.add(DM4);
        DM4.setForeground(new java.awt.Color(255, 255, 255));
        DM4.setText("ln");
        DM4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DM4ActionPerformed(evt);
            }
        });

        slDrawMode.setForeground(new java.awt.Color(102, 102, 102));
        slDrawMode.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDrawModeStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlDMLayout = new javax.swing.GroupLayout(pnlDM);
        pnlDM.setLayout(pnlDMLayout);
        pnlDMLayout.setHorizontalGroup(
            pnlDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DM3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DM2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlDMLayout.createSequentialGroup()
                .addComponent(slDrawMode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(DM4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDMLayout.setVerticalGroup(
            pnlDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDMLayout.createSequentialGroup()
                .addComponent(DM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DM2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DM3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DM4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(slDrawMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlLoF.setBackground(new java.awt.Color(102, 102, 102));

        cbLoF.setBackground(new java.awt.Color(102, 102, 102));
        cbLoF.setForeground(new java.awt.Color(255, 255, 255));
        cbLoF.setText("Lines of force");

        slLoF.setForeground(new java.awt.Color(102, 102, 102));
        slLoF.setMaximum(64);
        slLoF.setMinimum(4);
        slLoF.setValue(16);
        slLoF.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slLoFStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlLoFLayout = new javax.swing.GroupLayout(pnlLoF);
        pnlLoF.setLayout(pnlLoFLayout);
        pnlLoFLayout.setHorizontalGroup(
            pnlLoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbLoF)
            .addComponent(slLoF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlLoFLayout.setVerticalGroup(
            pnlLoFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoFLayout.createSequentialGroup()
                .addComponent(cbLoF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slLoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jRadioButton1.setBackground(new java.awt.Color(102, 102, 102));
        bgFieldTypeSelect.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Field strengt");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(102, 102, 102));
        bgFieldTypeSelect.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Potential");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2))
        );

        javax.swing.GroupLayout pnlToolsLayout = new javax.swing.GroupLayout(pnlTools);
        pnlTools.setLayout(pnlToolsLayout);
        pnlToolsLayout.setHorizontalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlChrgMouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRedraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlToolsLayout.createSequentialGroup()
                .addComponent(pnlLoF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlToolsLayout.setVerticalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addComponent(pnlRedraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLoF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChrgMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mbMain.setBackground(new java.awt.Color(102, 102, 102));
        mbMain.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(102, 102, 102));
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuItem1.setText("Новый проект");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Открыть");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Закрыть");
        jMenu1.add(jMenuItem3);

        mbMain.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Отменить");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Повторить");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator2);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItem6.setText("Удалить");
        jMenu2.add(jMenuItem6);

        mbMain.add(jMenu2);

        jMenu3.setText("Service");

        jMenuItem7.setText("Настройки");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Скриншот");
        jMenu3.add(jMenuItem8);

        mbMain.add(jMenu3);

        jMenu4.setText("About");
        mbMain.add(jMenu4);

        setJMenuBar(mbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnlTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // Помещаем заряды
    }//GEN-LAST:event_formMouseClicked

    static SettingsWindow wndSettings;
    static boolean tester = false;
    static boolean redrawAll = false;
    static boolean redrawFast = false;
    static int RFP = 1;
    static int FT = 1;
    static int DM = 2;
    static int CMV = 50;
    int ClcX = 0;
    int ClcY = 0;
    static Cursor cursor;

    private void ScrPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrPanelMouseClicked
        if (evt.getButton() == 1) {
            QVDialog.setLocation(
                    evt.getX() + DVQ.getLocation().x + super.getLocation().x - 10,
                    evt.getY() + DVQ.getLocation().y + super.getLocation().y - 40);
            QVDialog.setVisible(true);
            ClcX = evt.getX();
            ClcY = evt.getY();
        } else {
            for (int i = 0; i < Charges.count; i++) {
                Charges.arr[i].selected = false;
            }
            int num = Charges.numCTC(evt.getX(), evt.getY(), 4);
            if (num >= 0) {
                Charges.arr[num].selected = true;
            }
            ScrPanel.repaint();
        }
        //tester = !tester;
        //ScrPanel.repaint(); 
    }//GEN-LAST:event_ScrPanelMouseClicked

    private void DBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBtnCancelActionPerformed
        QVDialog.setVisible(false);
    }//GEN-LAST:event_DBtnCancelActionPerformed

    private void DBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBtnOKActionPerformed
        Charges.add(ClcX - 2, ClcY - 2, (float) DVQ.getValue());
        QVDialog.setVisible(false);
        ScrPanel.repaint();
    }//GEN-LAST:event_DBtnOKActionPerformed

    private void DM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DM1ActionPerformed
        DM = 1;
    }//GEN-LAST:event_DM1ActionPerformed

    private void DM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DM2ActionPerformed
        DM = 2;
    }//GEN-LAST:event_DM2ActionPerformed

    private void slDrawModeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDrawModeStateChanged
        CMV = slDrawMode.getValue();        // TODO add your handling code here:
    }//GEN-LAST:event_slDrawModeStateChanged

    private void DM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DM3ActionPerformed
        DM = 3;
    }//GEN-LAST:event_DM3ActionPerformed

    private void pnlRedrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRedrawMouseClicked
        redrawAll = true;
        ScrPanel.repaint();
    }//GEN-LAST:event_pnlRedrawMouseClicked

    private void btnFastRedrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFastRedrawActionPerformed
        redrawFast = true;
        redrawAll = true;
        RFP = slRFP.getValue();
        ScrPanel.repaint();
    }//GEN-LAST:event_btnFastRedrawActionPerformed

    private void btnRedrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedrawActionPerformed
        redrawAll = true;
        ScrPanel.repaint();
    }//GEN-LAST:event_btnRedrawActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        FT = 1;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        FT = 2;
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void DM4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DM4ActionPerformed
        DM = 4;        // TODO add your handling code here:
    }//GEN-LAST:event_DM4ActionPerformed

    private void DRBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRBtnOKActionPerformed
        Charges.add(ClcX - 2, ClcY - 2, (float) DVQ.getValue());
        QVDialog.setVisible(false);
        ScrPanel.repaint();
    }//GEN-LAST:event_DRBtnOKActionPerformed

    private void DRBtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DRBtnDelActionPerformed
        Charges.add(ClcX - 2, ClcY - 2, (float) DVQ.getValue());
        QVDialog.setVisible(false);
        ScrPanel.repaint();
    }//GEN-LAST:event_DRBtnDelActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        wndSettings.setLocation(super.getLocation().x + 40, super.getLocation().y + 40);
        wndSettings.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void slLoFStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slLoFStateChanged

    }//GEN-LAST:event_slLoFStateChanged

    private void slRFPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slRFPStateChanged
        RFP = slRFP.getValue();
    }//GEN-LAST:event_slRFPStateChanged

    boolean MLC = false;
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        MLC = !MLC;
        if (MLC) {
            Charges.arr[0].v = 1;
            Charges.arr[0].del = false;
        } else {
            Charges.arr[0].v = 0;
            Charges.arr[0].del = true;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ScrPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrPanelMouseDragged
       /* if (MLC) {
            redrawFast = true;
            redrawAll = true;
            RFP = slRFP.getValue();
            Charges.arr[0].x = evt.getX();
            Charges.arr[0].y = evt.getY();
            ScrPanel.repaint();
        } */
    }//GEN-LAST:event_ScrPanelMouseDragged

    private void ScrPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScrPanelMouseMoved
        if (MLC) {
            redrawFast = true;
            redrawAll = true;
            RFP = slRFP.getValue();
            Charges.arr[0].x = evt.getX();
            Charges.arr[0].y = evt.getY();
            ScrPanel.repaint();
        }
    }//GEN-LAST:event_ScrPanelMouseMoved

    static Chrgs Charges;

    public static void main(String args[]) {

        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage("chml_cross.gif");
        cursor = toolkit.createCustomCursor(image, new Point(13, 13), "Pencil");

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Charges = new Chrgs();
        Charges.add(-10, -10, 0);
        Charges.arr[0].del = true;

        /* Create and display the form */
        wndSettings = new SettingsWindow();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBtnCancel;
    private javax.swing.JButton DBtnOK;
    private javax.swing.JRadioButton DM1;
    private javax.swing.JRadioButton DM2;
    private javax.swing.JRadioButton DM3;
    private javax.swing.JRadioButton DM4;
    private javax.swing.JButton DRBtnDel;
    private javax.swing.JButton DRBtnOK;
    private javax.swing.JSpinner DRQ;
    private javax.swing.JSpinner DVQ;
    private javax.swing.JDialog QRDialog;
    private javax.swing.JDialog QVDialog;
    public javax.swing.JPanel ScrPanel;
    private javax.swing.ButtonGroup bgDrawModeSelect;
    private javax.swing.ButtonGroup bgFieldTypeSelect;
    private javax.swing.JButton btnFastRedraw;
    private javax.swing.JButton btnRedraw;
    private javax.swing.JCheckBox cbLoF;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JMenuBar mbMain;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlChrgMouse;
    private javax.swing.JPanel pnlDM;
    private javax.swing.JPanel pnlLoF;
    private javax.swing.JPanel pnlQPosNeg;
    private javax.swing.JPanel pnlRedraw;
    private javax.swing.JPanel pnlTools;
    private javax.swing.JSlider slDrawMode;
    private javax.swing.JSlider slLoF;
    private javax.swing.JSlider slRFP;
    // End of variables declaration//GEN-END:variables
}
